<?php
// Initialize the autoloader generated by composer
$loader = require 'vendor/autoload.php';
$loader->register();

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Dotenv\Dotenv;
use Petruk\Framework\Database;
use Petruk\Framework\Template;

// Initialize dotenv
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

// Initialize database connection
new Database();

$request = Request::createFromGlobals();

// Initialize template
$template = new Template();

// Petruk framework is now handling itself the request
$app = new Petruk\Framework\Core();

include('routes.php');

$response = $app->handle($request);
$response->send();